Repository compucorp/civihr-tasks-assignments, pull requests merged in 2018-09, with the labels that each got.

#421 PCHR-4166: Set Jenkins failure threshold to 0
  Jenkinsfile
Labels: bug, ready to test

#420 PCHR-4164: Rename deprecated Lodash function
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-assignment.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-assignment.controller.spec.js
Labels: ready to test, regression

#424 PCHR-3124: Delete Appraisals extension
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
  uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/DailyReminder.tpl
  uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Reminder/DailyReminderAppraisal.tpl
Labels: ready to test

#428 PCHR-4182: Menu Management Improvements
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Labels: ready to test
