Repository compucorp/civihr-tasks-assignments, pull requests merged in 2018-03, with the labels that each got.

#320 PCHR-3402: Remove non relevant tabs from the Workflow configuration screen
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Labels: enhancement

#324 PCHR-3382: Send Daily reminder Email to Recipient With Active Contract and With Primary Work Email
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
Labels: ready to test

#325 PCHR-3376: Update T&A Administer Menu Items
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Labels: ready to test

#331 PCHR-3481: Bump version to 1.7.5
  uk.co.compucorp.civicrm.tasksassignments/info.xml
Labels: ready to test

#330 Sync master with staging
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/info.xml
  uk.co.compucorp.civicrm.tasksassignments/scss/civihr/_civihr.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks.scss
Labels: ready to test, release
