Repository compucorp/civihr-tasks-assignments, pull requests merged in 2018-06, with the labels that each got.

#369 PCHR-3741: Staff Records Task Modal
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/document-list.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/task-list.controller.js
Labels: ready to test

#368 PCHR-3724: Sync styles with Shoreditch
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_shoreditch-imports.scss
Labels: bug, ready to test, regression

#370 PCHR-3769: Fix build process
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/js/tasks-assignments.build.js
  uk.co.compucorp.civicrm.tasksassignments/js/tasks-notification-badge.build.js
Labels: ready to test

#371 PCHR-3162: Configurability Changes - Tool Icon Integration
  uk.co.compucorp.civicrm.tasksassignments/api/v3/Document.php
  uk.co.compucorp.civicrm.tasksassignments/api/v3/Task.php
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/document-list.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-task.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/task-list.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-document.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-task.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_forms.scss
  uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html
  uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
Labels: ready to test

#372 PCHR-3781: Bump version to 1.7.7
  uk.co.compucorp.civicrm.tasksassignments/info.xml
Labels: ready to test

#373 Sync master with staging
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Form/Options.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/api/v3/Document.php
  uk.co.compucorp.civicrm.tasksassignments/api/v3/Task.php
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/info.xml
  uk.co.compucorp.civicrm.tasksassignments/js/CRM/Form/Options.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/crm-tasks-workflows.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-notification-badge.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/controllers/casetype.extended.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/decorators/route.decorator.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/document-list.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-document.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-task.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/task-list.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-notification-badge.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-notification-badge/app.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-notification-badge/components/tasks-notification-badge.component.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-notification-badge/modules/components.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-notification-badge/modules/config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-notification-badge/modules/settings.js
  uk.co.compucorp.civicrm.tasksassignments/js/tasks-assignments.build.js
  uk.co.compucorp.civicrm.tasksassignments/js/tasks-notification-badge.build.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/controllers/casetype.extended.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/decorators/route.decorator.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-document.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-task.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/component/tasks-notification-badge.component.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/test-main.js
  uk.co.compucorp.civicrm.tasksassignments/scss/civihr/partials/_datepicker.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civihr/partials/_forms.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_forms.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_shoreditch-imports.scss
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
  uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html
  uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/document.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
  uk.co.compucorp.civicrm.tasksassignments/views/tasks-notification-badge/components/tasks-notification-badge.html
Labels: release

#375 PCHR-3811: Update the civihr repo URL
  Jenkinsfile
Labels: enhancement, ready to test

#376 PCHR-3543: Update T&A Settings
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Labels: ready to test

#379 PCHR-3836: Add Upgrader for Case Type Custom Field
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Labels: ready to test

#378 PCHR-3535: Tasks And Assignments Settings
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Labels: ready to test
