Repository compucorp/civihr-tasks-assignments, pull requests merged in 2018-11, with the labels that each got.

#433 PCHR-4356: Fix regression issues when syncing with latest Shoreditch release
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
Labels: ready to test

#434 CiviHR 1.7.13
  uk.co.compucorp.civicrm.tasksassignments/info.xml
Labels: release

#435 PCHR-4243: Fix AngularJS 1.6 router links
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/DashboardSwitcher.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/MyDocuments.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/MyTasks.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TASettingsTest.php
Labels: regression
