Repository compucorp/civihr-tasks-assignments, pull requests merged in 2018-02, with the labels that each got.

#311 PCHR-3259: Use lint staged for pre-commit linters
  .gitignore
  package-lock.json
  package.json
  uk.co.compucorp.civicrm.tasksassignments/js/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/package.json
Labels: enhancement, ready to test

#313 PCHR-3284: Select current user as target contact in workflow modal
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-assignment.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-assignment.controller.spec.js
Labels: bug, ready to test, regression

#314 PCHR-3057: Fix JS error when when value for 'Number of days..' is empty
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.values.js
Labels: bug, ready to test

#312 PCHR-3246: Implement stylelint for SASS files
  package-lock.json
  package.json
Labels: ready to test

#307 PCHR-3061: Task and Assignment admin styles
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_lists.scss
  uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html
  uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/taskMigrate.html
Labels: bug

#316 PCHR-2819: Contact Page Actions Epic
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/main.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-assignment.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/main.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-assignment.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.documentList.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html
Labels: ready to test

#318 Sync master with staging
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Jenkinsfile
  package-lock.json
  package.json
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/Files.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Reminder.php
  uk.co.compucorp.civicrm.tasksassignments/css/civitasks.css
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/info.xml
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/document.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/main.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-assignment.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.values.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/document.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/main.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-assignment.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/package.json
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/modules/_civihr-ui-select.scss
  uk.co.compucorp.civicrm.tasksassignments/scss/civitasks/partials/_lists.scss
  uk.co.compucorp.civicrm.tasksassignments/views/contact/documents.html
  uk.co.compucorp.civicrm.tasksassignments/views/contact/tasks.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/calendar.documentList.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/documents.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/key-dates.html
  uk.co.compucorp.civicrm.tasksassignments/views/dashboard/tasks.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
  uk.co.compucorp.civicrm.tasksassignments/views/modal/taskMigrate.html
Labels: ready to test

#317 PCHR-3353: Set Custom Groups to Reserved
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Labels: ready to test
