Repository compucorp/civihr-tasks-assignments, pull requests merged in 2018-04, with the labels that each got.

#333 PCHR-3416: Hide reserved activity types
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/Options.php
Labels: enhancement, ready to test

#332 PCHR-3469: Automatically select tasks assignee when creating workflows
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/main.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-assignment.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/main.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-assignment-activity.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/modal/modal-assignment.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/mocks/data/option-values.data.js
  uk.co.compucorp.civicrm.tasksassignments/views/modal/assignment.html
Labels: enhancement, ready to test

#334 PCHR-3405: Rename workflow statuses
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
Labels: enhancement, ready to test

#336 PCHR-3529: Activity dropdown changes
  package-lock.json
  package.json
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/crm-tasks-workflows.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/configs/crm-case-type.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/controllers/casetype.extended.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/modules/crm-tasks-workflows.controllers.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/modules/crm-tasks-workflows.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/controllers/casetype.extended.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/controllers/case-type.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/data/activity-options.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/modules/crm-case-type.module.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/modules/crm-tasks-workflows.mocks.module.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/assignments.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/document-list.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/document.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/main.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-assignment-activity.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-assignment.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-document.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-task.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/tasks-list.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/filters/date-field.filter.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/filters/date-type.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/filters/ownership.filter.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/app-settings.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/assignment.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/contact.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/document.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/key-dates.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/option-values.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/task.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/assignment.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/contact.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/document.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/file.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/task.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/assignment.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/contact.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/document.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/settings.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/task.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/test-main.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/test-main.js
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Labels: enhancement, ready to test

#338 PCHR-3575: Hide Columns and Show component type
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/crm-tasks-workflows.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/configs/crm-case-type.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/controllers/casetype.extended.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/decorators/route.decorator.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/modules/crm-tasks-workflows.decorator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/controllers/casetype.extended.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/controllers/case-type.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/data/activity-options.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/data/document-activity-options.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/data/task-activity-options.data.js
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Labels: enhancement, ready to test

#343 PCHR-3162: Configurability Changes
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Labels: ready to test

#345 PCHR-3596: Rename T&A Modal
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-dialog.controller.js
Labels: enhancement, ready to test

#346 PCHR-3572: Display case closed message
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/main.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-assignment.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/controllers/main.controller.spec.js
Labels: enhancement, ready to test

#349 PCHR-3592: Add slack notifications to Jenkins #2579
  Jenkinsfile
Labels: ready to test

#352 PCHR-3635: Fix hoek GitHub security vulnerability warning
  package-lock.json
  package.json
Labels: ready to test

#354 PCHR-3369: Tasks and Workflows UX improvements
  package-lock.json
  package.json
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Page/Options.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/crm-tasks-workflows.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/controllers/casetype.extended.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/decorators/route.decorator.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/modules/crm-tasks-workflows.controllers.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/modules/crm-tasks-workflows.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/modules/crm-tasks-workflows.decorator.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-dialog.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/controllers/casetype.extended.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/controllers/case-type.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/data/document-activity-options.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/data/task-activity-options.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/modules/crm-case-type.module.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/mocks/modules/crm-tasks-workflows.mocks.module.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/assignments.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/document-list.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/document.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/main.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-assignment.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-document.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-task.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/tasks-list.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/filters/date-field.filter.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/filters/date-type.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/filters/ownership.filter.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/app-settings.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/assignment.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/contact.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/document.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/key-dates.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/data/task.data.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/assignment.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/contact.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/document.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/file.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/mocks/fabricators/task.fabricator.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/assignment.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/contact.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/document.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/settings.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/task.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/test-main.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/test-main.js
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
Labels: enhancement, new feature, ready to test

#358 PCHR-3638: Bump ext version
  uk.co.compucorp.civicrm.tasksassignments/info.xml
Labels: ready to test
