Repository compucorp/civihr-tasks-assignments, pull requests merged in 2018-07, with the labels that each got.

#381 PCHR-3849: Google Analytics Implementation - Milestone 1
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.dashboard.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.documents.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.settings.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.tasks.config.js
Labels: ready to test

#382 PCHR-3926: Add karma spec reporter to JS unit tests
  package-lock.json
  package.json
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/karma.conf.js
Labels: enhancement, ready to test

#383 PCHR-3601: Remove Probation Custom Group
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.run.js
  uk.co.compucorp.civicrm.tasksassignments/xml/probation.xml
Labels: ready to test

#384 PCHR-3662: Change title of Task modal based on mode
  package-lock.json
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-task.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-task.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
Labels: bug, ready to test

#380 PCHR-3429: CiviCRM upgrade
  Jenkinsfile
  uk.co.compucorp.civicrm.tasksassignments/CRM/Activity/Form/ActivityView.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Assignment.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/api/v3/TASettings.php
  uk.co.compucorp.civicrm.tasksassignments/settings/tasksandassignments.setting.php
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
  uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TASettingsTest.php
Labels: ready to test

#387 PCHR-3542: Custom Group Updates
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.run.js
  uk.co.compucorp.civicrm.tasksassignments/xml/probation.xml
Labels: ready to test

#388 PCHR-3979: Bump version to 1.7.8
  uk.co.compucorp.civicrm.tasksassignments/info.xml
Labels: ready to test

#389 Sync master with staging
  Jenkinsfile
  package-lock.json
  package.json
  uk.co.compucorp.civicrm.tasksassignments/CRM/Activity/Form/ActivityView.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Assignment.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/api/v3/TASettings.php
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
  uk.co.compucorp.civicrm.tasksassignments/info.xml
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-task.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.dashboard.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.documents.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.run.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.settings.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.tasks.config.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/modal/modal-task.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/settings/tasksandassignments.setting.php
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
  uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TASettingsTest.php
  uk.co.compucorp.civicrm.tasksassignments/views/modal/task.html
  uk.co.compucorp.civicrm.tasksassignments/xml/probation.xml
Labels: ready to test, release

#390 Revert "PCHR-3542: Custom Group Updates"
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.run.js
  uk.co.compucorp.civicrm.tasksassignments/xml/probation.xml
Labels: ready to test

#391 Sync master with staging
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.run.js
  uk.co.compucorp.civicrm.tasksassignments/xml/probation.xml
Labels: ready to test, release

#386 PCHR-3973: Hide Vacancy Workflow types
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Hook/PageRun/CustomFieldIds.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Hook/PageRun/Resources.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/crm-tasks-workflows.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/decorators/route.decorator.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/crm-tasks-workflows/modules/crm-tasks-workflows.constants.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/decorators/route.decorator.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/globals.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/crm-tasks-workflows/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/tasksassignments.php
  uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/Hook/PageRun/CustomFieldIdsTest.php
  uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/Hook/PageRun/ResourcesTest.php
Labels: enhancement, ready to test

#392 PCHR-3942: Fix paths to org.civirm.reqangular files
  package-lock.json
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/karma.conf.js
Labels: enhancement, ready to test

#344 PCHR-3406: mark case as closed
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/BAO/Task.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/Case.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/CaseType.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/OptionGroup.php
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Test/Fabricator/OptionValue.php
  uk.co.compucorp.civicrm.tasksassignments/api/v3/Task.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/main.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/controllers/modal/modal-assignment.controller.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/controllers/main.controller.spec.js
  uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/CRM/Tasksassignments/BAO/TaskTest.php
  uk.co.compucorp.civicrm.tasksassignments/tests/phpunit/api/v3/TaskTest.php
Labels: new feature, ready to test

#396 PCHR-4008: CiviCRM 5.3.1 upgrade
  Jenkinsfile
  uk.co.compucorp.civicrm.tasksassignments/CRM/Activity/Form/ActivityView.php
Labels: ready to test

#397 PCHR-4026: Bump version to 1.7.9
  uk.co.compucorp.civicrm.tasksassignments/info.xml
Labels: ready to test

#398 Sync master with staging
  Jenkinsfile
  package-lock.json
  uk.co.compucorp.civicrm.tasksassignments/CRM/Activity/Form/ActivityView.php
  uk.co.compucorp.civicrm.tasksassignments/info.xml
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/karma.conf.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/karma.conf.js
Labels: ready to test, release

#394 PCHR-3941: Add doc for crm-tasks-workflows build process
  uk.co.compucorp.civicrm.tasksassignments/gulpfile.js
Labels: enhancement, ready to test

#399 PCHR-3944: Update to AngularJS v1.7
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-notification-badge.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.core.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/vendor/angular/angular-ui-router.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-notification-badge/components/tasks-notification-badge.component.js
  uk.co.compucorp.civicrm.tasksassignments/js/tasks-assignments.build.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/contact.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/document.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/settings.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/services/task.service.spec.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-assignments/test-main.js
  uk.co.compucorp.civicrm.tasksassignments/js/test/tasks-notification-badge/component/tasks-notification-badge.component.spec.js
  uk.co.compucorp.civicrm.tasksassignments/templates/CRM/Tasksassignments/Page/Dashboard.tpl
Labels: enhancement, ready to test

#402 PCHR-3542: Custom Group Updates
  uk.co.compucorp.civicrm.tasksassignments/CRM/Tasksassignments/Upgrader.php
  uk.co.compucorp.civicrm.tasksassignments/js/dist/tasks-assignments.min.js
  uk.co.compucorp.civicrm.tasksassignments/js/src/tasks-assignments/modules/tasks-assignments.run.js
  uk.co.compucorp.civicrm.tasksassignments/xml/probation.xml
Labels: ready to test
